exports.CONFIG = {
    PORT: 3000
}

exports.FIREBASE_TABLES = [
  "superAdmin",
  "alerts",
  "alertHistory",
  "devices",
  "deviceConfig",
  "energyHistory",
  "transactions",
  "contactUs",
  "ratings",
  "reports"
]

exports.MYSQL_TABLES = [
  "tbl_admin",
  "tbl_alerthistory",
  "tbl_alerts",
  "tbl_contacts",
  "tbl_devices",
  "tbl_devicesconfig",
  "tbl_energyhistory",
  "tbl_ratings",
  "tbl_reports",
  "tbl_transactions",
  "tbl_users"
]

exports.MYSQL_TABLES_COLUMNS = [
  [
    "admin_id",
    "username",
    "email",
    "password",
    "backup_email",
    "full_name"
  ],
  [
    "id",
    "device_id",
    "max_batt",
    "min_batt",
    "max_temp",
    "min_temp"
  ],
  [
    "alert_id",
    "device_id",
    "date_time",
    "content",
    "threat"
  ],
  [
    "contact_id",
    "user_id",
    "subject",
    "message",
    "from_email",
    "hasRead",
    "responded",
    "photo_url",
    "timestamp"
  ],
  [
    "device_id",
    "name",
    "building",
    "location",
    "current",
    "volt",
    "power",
    "energy",
    "temperature",
    "battVolt",
    "status",
    "last_updated",
    "date_added",
    "version"
  ],
  [
    "deviceConfig_id",
    "device_id",
    "device_enabled",
    "device_alert_enabled",
    "max_batt",
    "min_batt",
    "max_temp",
    "min_temp",
    "minute_per_peso",
    "samples_per_hour",
    "update_gap_seconds"
  ],
  [
    "energyHistory_id",
    "device_id",
    "date_time",
    "current",
    "voltage",
    "energy_accumulated",
    "temperature"
  ],
  [
    "rating_id",
    "user_id",
    "date_time",
    "email",
    "fullname",
    "building",
    "location",
    "comment",
    "rate",
    "photo_url"
  ],
  [
    "report_id",
    "device_id",
    "user_id",
    "date_time",
    "fullname",
    "email",
    "description",
    "type",
    "status",
    "urgencyLevel",
    "photo_url"
  ],
  [
    "transaction_id",
    "device_id",
    "date_time",
    "amount"
  ],
  [
    "user_id",
    "email",
    "full_name"
  ]
]